// <auto-generated />
namespace BITCollege_RS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedNextAvailableNumberMethod : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedNextAvailableNumberMethod));
        
        string IMigrationMetadata.Id
        {
            get { return "202010032210434_addedNextAvailableNumberMethod"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
